// week1-vue/src/App.vue
<script setup>
import { ref } from 'vue';
import Form from './components/Form/Form.vue'
import TaskItem from './components/TaskItem/TaskItem.vue';

let tasks = ref([]);
let id = ref(0);
let editingTask = ref(null);

function addTask(inputValue) {
  if (!inputValue.trim()) {
    alert('Please write a task');
    return;
  }

  tasks.value.push(
    {
      id: ++id.value,
      title: inputValue.trim(),
      completed: false
    }
  );
}

function deleteTask(id) {
  tasks.value = tasks.value.filter(task => task.id !== id);
}
</script>

<template>
  <div class="todo-container">
    <Form 
      @addTask="addTask" 
      :editingTask="editingTask"
      />
    <div class="task-list">
      <TaskItem 
        v-for="task in tasks" 
        :key="task.id" 
        :task="task"
         @deleteTask="deleteTask"
      />
    </div>
  </div>
</template>

// week1-react/src/App.jsx
import "./App.css";
import TodoForm from "./components/TodoForm/TodoForm";
import TaskItem from "./components/TaskItem/TaskItem";
import { useState, useRef } from "react";

function App() {
  const ID = useRef(0);
  const [tasks, setTasks] = useState([]);

  function addTodo(inputValue) {
    if (inputValue === '') {
      alert("Please Write a Task Name");
      return;
    }
    
    const newTodo = {
      id: ++ID.current,
      text: inputValue,
      completed: false,
    };

    setTasks((prev) => [...prev, newTodo]);
  }

  function deleteTodo(id) {
    setTasks(tasks => {
      return tasks.filter(task => task.id !== id);
    })
  }

  function changeStatus(id) {
    setTasks(tasks =>
      tasks.map((task) => {
        if (task.id === id) {
          return {
            ...task,
            completed: !task.completed,
          };
        } else {
          return task;
        }
      }),
    );
  }

  return (
    <div className="todo-container">
      <h1>To Do</h1>
      <TodoForm addTodo={addTodo}></TodoForm>
      <div className="task-list">
        {tasks.map((item) => {
          return (
            <TaskItem
              text={item.text}
              completed={item.completed}
              changeStatus={changeStatus}
              deleteTodo={deleteTodo}
              id={item.id}
              key={item.id}
            ></TaskItem>
          );
        })}
      </div>
    </div>
  );
}

export default App;
