// week1-vue/src/components/TaskItem/TaskItem.vue
<script setup>
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { faXmark } from '@fortawesome/free-solid-svg-icons';

const props = defineProps({
    task: Object
})

const emits = defineEmits(['deleteTask']);
function handleDelete(task) {
    emits('deleteTask', task)
}
</script>

<template>
    <div class="task">
        {{ props.task.title }}
        <div>
            <FontAwesomeIcon :icon="faXmark" @click="handleDelete(props.task.id)" class="delete" />
        </div>
    </div>
</template>

<style scoped>
.task-name {
    font-size: 20px;
}

.edit {
    color: #FF643A;

}

.delete {
    color: red;
    cursor: pointer;
}
</style>

// week1-react/src/components/TaskItem/TaskItem.jsx
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faXmark } from '@fortawesome/free-solid-svg-icons';
import './TaskItem.css'

function TaskItem({ text, completed, changeStatus, deleteTodo, id }) {
    function handleOnChange(id) {
        changeStatus(id);
    }

    function handleDelete(id) {
        deleteTodo(id);
    }

    return (
        <div className="task">
            <input
                type="checkbox"
                checked={completed}
                onChange={() => handleOnChange(id)}
            />
            <p
                className='task-name'
                style={{ textDecoration: completed ? "line-through" : "none" }}
            >
                {text}
            </p>
            {/* <FontAwesomeIcon 
                icon={faPenToSquare} 
                className='edit'
            /> */}

            <FontAwesomeIcon
                className='delete'
                icon={faXmark}
                style={{ cursor: "pointer" }}
                onClick={() => handleDelete(id)}
            />
        </div>
    );
}

export default TaskItem
